# Generated by Django 5.2.14 on 2026-05-21 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('short_description', models.CharField(help_text='A one-liner for the grid card.', max_length=255)),
                ('full_description', models.TextField(help_text='Detailed breakdown of architecture and problem solved.')),
                ('tech_stack', models.CharField(help_text='Comma separated (e.g., Python, Django, Gemini 2.5)', max_length=255)),
                ('github_link', models.URLField(blank=True, null=True)),
                ('live_link', models.URLField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='projects/')),
                ('is_featured', models.BooleanField(default=False, help_text='Check this to give it the massive hero-grid treatment (e.g., AI Research Studio).')),
                ('order', models.IntegerField(default=0, help_text='Lower numbers appear first.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
